services:
  postgres:
    image: postgres:14
    container_name: postgres-transparency
    ports:
      - "5432:5432"   
    environment:
      POSTGRES_DB: transparency_db
      POSTGRES_USER: transparency_user
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
